# https://github.com/CircleCI-Public/node-orb/blob/master/src/examples/run_tests_with_yarn.yml

version: 2.1

parameters:
  pull_request:
    type: boolean
    default: false

orbs:
  node: circleci/node@5.2.0

commands:
  setup-corepack:
    steps:
      - run:
          name: Enable Corepack
          command: sudo corepack enable
      - run:
          name: Prepare yarn
          command: sudo corepack prepare yarn@4.3.1 --activate
      - run:
          name: Install Dependencies
          command: yarn install

jobs:
  setup:
    executor:
      name: node/default
      tag: '20.16.0'
    steps:
      - checkout
      - setup-corepack

  # debug:
  #   executor:
  #     name: node/default
  #     tag: '20.16.0'
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run:
  #         name: Print Working Directory
  #         command: pwd
  #     - run:
  #         name: List Files
  #         command: ls -la
  #     - run:
  #         name: Print Corepack Version
  #         command: corepack --version
  #     - run:
  #         name: Print Yarn Version
  #         command: yarn --version

  lint-staged:
    executor:
      name: node/default
      tag: '20.16.0'
    working_directory: ~/repo
    steps:
      - checkout
      - setup-corepack
      - run:
          name: Check ESLint
          command: yarn lint
      - run:
          name: Check Prettier
          command: yarn format

  test:
    executor:
      name: node/default
      tag: '20.16.0'
    working_directory: ~/repo
    steps:
      - checkout
      - setup-corepack
      - run:
          name: Run Tests
          command: yarn test

workflows:
  guardia:
    jobs:
      - setup
      - lint-staged:
          requires:
            - setup
          filters:
            branches:
              ignore: main
      - test:
          requires:
            - setup
          filters:
            branches:
              ignore: main
